GCC5 + Mac, first attempt
This is only an attempt that might work because OpenMVG travis only tasts Xcode < 11 at the present date.
Latest Xcode 11 currently has bugs with GCC which prevents for
compiling. These are the curent errors with Xcode 11, which will be fixed soon upstream
see Homebrew/homebrew-core#44579

[  0%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinBuild.cpp.o
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:110,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:66,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/cstdlib:75,
                 from /Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinBuild.cpp:7:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:443:34: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  443 | int     getiopolicy_np(int, int) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:449:39: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  449 | int     setiopolicy_np(int, int, int) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);